### ISSUE TITLE
broadcast unit test failure - patching transaction with default global properties

### ISSUE THREAD

**Issue by 0xweb3builder** [norestlabs/knowledgr-js#17]
```
steem.broadcast: patching transaction with default global properties works:
     RPCError: Bad Cast:Invalid cast from type 'array_type' to Object
      at new RPCError (src/api/transports/http.js:9:25)
      at src/api/transports/http.js:48:13
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Need to update unit test.

**Comment by 0xweb3builder** [comment]
Verified by 6469bd8177376022e906d39d67c3c3e86fd57e87
